//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSGP_BMM.Models.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class dbo_Members
    {
        public int MemberID { get; set; }

        [DisplayName("Last Name")]
        public string Lastname { get; set; }
        
        [DisplayName("First Name")]
        public string Firstname { get; set; }

        [DisplayName("Middle Name")]
        public string Middlename { get; set; }

        [DataType(DataType.Date)]
        [DisplayName("Start Date")]
       
        public Nullable<System.DateTime> Startdate { get; set; }

        [DisplayName("End Date")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> Enddate { get; set; }

        [DisplayName("Course")]
        public string Course { get; set; }

        [DisplayName("Office Asigned")]
        public string Assignment { get; set; }
    }
}
